trigger:
  - workspace_publish

variables:
  system.debug: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Synapse workspace deployment@2
  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: 'syn-dev-eus01'
    azureSubscription: 'Promit''s Cloud(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'TEST-QA-EUS-RG'
    TargetWorkspaceName: 'syn-qa-eus01'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'

- script: |
    git config --global user.email "promit.xi@gmail.com"
    git config --global user.name "Promit"
    git checkout QA-master
    git add .
    git commit -m "Deployment to QA-Master"
    git push origin QA-master
  displayName: 'Git push to QA-Master'
