# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - workspace_publish

variables:
  system.debug: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Synapse workspace deployment@2
  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: 'syn-dev-eus01'
    azureSubscription: 'Promit''s Cloud(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'TEST-QA-EUS-RG'
    TargetWorkspaceName: 'syn-qa-eus01'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'